const ADD_ALL_CAST_INFO_TYPE = 'ADD_ALL_CAST_INFO_TYPE';
const ADD_OWNE_INFO = 'ADD_OWNE_INFO';
const CURRENT_CHAT_UPDATE = 'CURRENT_CHAT_UPDATE';
const PUSH_SINGLE_MESSAGE = 'PUSH_SINGLE_MESSAGE';
const UPDATE_CITY_LIST = 'UPDATE_CITY_LIST';
const SEARCH_FILTER_DATA = 'SEARCH_FILTER_DATA';
const TAG_VALUES = 'TAG_VALUES';
const ALL_NOTICATION = 'ALL_NOTICATION';
const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
const ADD_USER_AS_SELECTED_CAST = 'ADD_USER_AS_SELECTED_CAST';
const ALL_GIFT_ICON = 'ALL_GIFT_ICON';
const SIGN_IN_METHOD = 'SIGN_IN_METHOD';

export default {
  ADD_ALL_CAST_INFO_TYPE,
  ADD_OWNE_INFO,
  CURRENT_CHAT_UPDATE,
  PUSH_SINGLE_MESSAGE,
  UPDATE_CITY_LIST,
  SEARCH_FILTER_DATA,
  TAG_VALUES,
  ALL_NOTICATION,
  UPDATE_NOTIFICATION,
  ADD_USER_AS_SELECTED_CAST,
  ALL_GIFT_ICON,
  SIGN_IN_METHOD,
};
