import EStyleSheet from 'react-native-extended-stylesheet';
import {Dimensions, Platform} from 'react-native';
const screenWidth = Math.round(Dimensions.get('window').width);

export default EStyleSheet.flatten(
  EStyleSheet.create({
    centerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
    },
    SpaceBetweenContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
    },
    ProfileContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
      margin: 35,
    },
    profilePic: {
      marginBottom: 15,
    },
    UserNameText: {
      color: '$primaryBgColor',
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 10,
    },
    titleContinerText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    coinContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
    },
    coinContainerTop: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 20,
      width: '100%',
      backgroundColor: 'white',
      paddingBottom: 20,
      marginBottom: 0,
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
    },
    coinContainerText: {
      paddingLeft: 20,
    },
    stretch: {
      width: 50,
      height: 50,
    },
    stretchLOve: {
      width: 270,
      height: 50,
    },
    heartsText: {
      paddingHorizontal: 20,
    },
    OnClikText: {
      alignItems: 'center',
      paddingLeft: 20,
    },
    profilePicImage: {
      width: 150,
      height: 150,
      borderRadius: 75,
      backgroundColor: '$secondaryBgColor',
    },
    topOptionsContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    topOptions: {
      backgroundColor: '$primaryBgColor',
      width: 70,
      height: 70,
      borderRadius: 75,
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    topOptionsText: {
      marginTop: 12,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#555',
    },
    editIcon: {
      backgroundColor: '$primaryBgColor',
      width: 40,
      height: 40,
      padding: 12,
      borderRadius: 25,
      position: 'absolute',
      right: 0,
      bottom: 0,
    },
    balanceSection: {
      width: '50%',
      padding: 15,
      backgroundColor: 'white',
    },
    hourlyRate: {
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 15,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    comments: {
      width: screenWidth - 65,
      fontSize: 15,
      marginLeft: 30,
      borderWidth: 1.5,
      marginRight: 30,
      paddingLeft: 20,
      borderRadius: 5,
      paddingBottom: 15,
      fontWeight: 'bold',
      borderColor: '#ccc',
      backgroundColor: '#fff',
    },
    optionHolder: {
      marginTop: 30,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    options: {
      height: 38,
      width: screenWidth / 2 - 37,
      borderRadius: 5,
      borderWidth: 0.5,
      textAlign: 'center',
      borderColor: '#bbb',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    withdrawMonent: {
      backgroundColor: '#fff',
      padding: 20,
      borderRadius: 4,
    },
    withdrawMonentTitle: {
      fontSize: 20,
      color: '$primaryBgColor',
      textAlign: 'left',
      paddingBottom: 10,
    },
    withdrawMonentInput: {
      marginTop: 10,
      fontSize: 15,
      borderWidth: 1,
      padding: 10,
      borderRadius: 5,
      borderColor: '#ccc',
      backgroundColor: '#fff',
      color: '$primaryBgColor',
    },
    withdrawMonentButton: {
      height: 38,
      borderRadius: 5,
      borderWidth: 0.5,
      textAlign: 'center',
      borderColor: '#bbb',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
      paddingVertical: 5,
    },
    withdrawMonentButtonMain: {
      marginLeft: 10,
      backgroundColor: '$primaryBgColor',
    },
    withdrawMonentButtonColor: {
      color: '#fff',
    },
    profileData: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: '#aaa',
    },
    iconBg: {
      marginTop: 10,
      color: '#43C5FF',
      fontWeight: 'bold',
    },
    pointContainter: {
      justifyContent: 'space-around',
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: '#aaa',
      paddingVertical: 25,
      backgroundColor: '#fff',
    },
    pointColumn: {
      justifyContent: 'center',
    },
    pointColumnHeaderNumber: {
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 25,
    },
    addButtonPoints: {
      marginTop: 10,
      color: '$primaryBgColor',
      fontWeight: 'bold',
      textAlign: 'center',
    },
  }),
);
